### ISSUE TITLE
Idea for checking expiration dates of TLS certificates

### ISSUE THREAD

**Issue by gonzalo-bulnes** [kushaldas/sdstatus#4]
Hi @kushaldas @conorsch!

As was thinking about the [apt.freedom.press certificate expiration][cert] this morning and it occurred to me that maybe a certificate expiration date checker (like this one, but that would check the certificates expiration date / validity) could be run periodically to bring attention on certificates getting close to expiration.

_Considering that probably only a few certificates would expire every year, my first thought would be to run it with the weekly tasks of the build of a repo that gets a lot of attention (say SecureDrop Core). Red builds are a sure way to get attention of things, but admittedly hooking into an unrelated repo's tooling is not necessarily a very clean way to proceed._

What do you think? 

---

I played a bit with **sdstatus** as a pretext to write some concurrent code some time ago. I extracted the individual status check and output formatting apart from the concurrency management –I called that last part _scanner_. _I've been meaning to offer comparing notes for a while, by the way, but haven't really taken the time to turn my spike from the [branch where it lives][spike] into a proper PR._

I believe that it shouldn't be too hard to write a "certificate check" for that purpose in the lines of the "status check" that **sdstatus** uses, and I'd be happy to take a closer look if it seems it could be useful. 🙂 

References:

-  [`x509.Certificate.NotAfter`][ref]

  [cert]: https://securedrop.org/news/advisory-temporary-certificate-error-aptfreedompress/
  [spike]: https://github.com/gonzalo-bulnes/scanner/tree/spike-sdstatus-2/cmd
  [ref]: https://golang.org/pkg/crypto/x509/#Certificate
  [poc]: https://github.com/gonzalo-bulnes/scanner/tree/spike-certificate-check/cmd

**Edit**: [proof of concept][poc] - usage: `go run cmd/main.go` from the branch.

**Comment by conorsch** [comment]
Hello, @gonzalo-bulnes! Thanks for the suggestion. Regarding the apt expiry, we have added monitoring for that endpoint, with logic lifted from https://serverlesscode.com/post/ssl-expiration-alerts-with-lambda/ (so, Python, rather than Go). The repo where we store those types of tools is private, so unfortunately I cannot share a URL with you. 

Your suggestion to add certificate monitoring to sdstatus is a good one. To be clear, we're not currently using sdstatus in our automatic monitoring of production SecureDrop instances—we use Icinga for that—but I do use it frequently myself on the command-line, and we may well pull it into the Icinga setup in the future. Having an early warning about an upcoming cert expiry for an SD instance would aid our support team in reaching out proactively to SD admins to recommend renewal.  

@kushaldas Can I get a review of https://github.com/freedomofpress/sdstatus/pull/3 ? After that lands, @gonzalo-bulnes, would be a great time to try adding cert checking logic to the tool!

**Comment by gonzalo-bulnes** [comment]
> Regarding the apt expiry, we have added monitoring for that endpoint [...]

Nice. I noticed some cards in the [Team Board](https://github.com/orgs/freedomofpress/projects/1) that point to private repos, this makes complete sense. 👍 

> Having an early warning about an upcoming cert expiry for an SD instance would aid our support team in reaching out proactively to SD admins to recommend renewal.

💡 I hadn't thought of that!

I'll keep an eye on this and open a proper PR when there is more clarity on #3. I started my own spikes from there indeed. 🙂 
Thanks for the additional context @conorsch !

**Comment by gonzalo-bulnes** [comment]
I'll close this issue that was really meant for discussion. Please re-open and/or `@` me if needed : )
